name: Blog Post Notification

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
#     paths:
#       - 'content/blog/**.mdx'

jobs:
  extract-metadata:
    runs-on: ubuntu-latest
    outputs:
      metadata: ${{ steps.metadata.outputs.metadata }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 3  # Need at least 3 commits to detect changes bc docs are created in a different branch, then commited to dev and lastly to main.
      
      - name: Extract blog metadata
        id: metadata
        uses: ./.github/actions/extract-blog-metadata
        with:
          blog_directory: 'content/blog'

      # Optional debug step
      - name: Debug metadata
        run: |
          echo "Metadata output: ${{ steps.metadata.outputs.metadata }}"

  send-notifications:
    needs: extract-metadata
    if: ${{ needs.extract-metadata.outputs.metadata != '[]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Send notifications
        uses: ./.github/actions/send-blog-notifications
        with:
          blog_metadata: ${{ needs.extract-metadata.outputs.metadata }}
          database_url: ${{ secrets.DATABASE_URL }}
          resend_api_key: ${{ secrets.RESEND_API_KEY }}
          site_url: 'https://automated-aquarium.com'
          from_email: 'newsletter-no-reply@automated-aquarium.com'